// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: docs.sql

package db

import (
	"context"
)

const createDoc = `-- name: CreateDoc :exec
INSERT INTO docs (id, workspace_id, path, title, content_hash, created_by)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDocParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Path        string `json:"path"`
	Title       string `json:"title"`
	ContentHash string `json:"content_hash"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) CreateDoc(ctx context.Context, arg CreateDocParams) error {
	_, err := q.db.ExecContext(ctx, createDoc,
		arg.ID,
		arg.WorkspaceID,
		arg.Path,
		arg.Title,
		arg.ContentHash,
		arg.CreatedBy,
	)
	return err
}

const getDoc = `-- name: GetDoc :one
SELECT id, workspace_id, path, title, content_hash, created_by,
       created_at, updated_at, deleted_at
FROM docs
WHERE id = ? AND workspace_id = ?
`

type GetDocParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetDoc(ctx context.Context, arg GetDocParams) (Doc, error) {
	row := q.db.QueryRowContext(ctx, getDoc, arg.ID, arg.WorkspaceID)
	var i Doc
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Path,
		&i.Title,
		&i.ContentHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDocsByWorkspace = `-- name: ListDocsByWorkspace :many
SELECT id, workspace_id, path, title, content_hash, created_by,
       created_at, updated_at, deleted_at
FROM docs
WHERE workspace_id = ? AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListDocsByWorkspace(ctx context.Context, workspaceID string) ([]Doc, error) {
	rows, err := q.db.QueryContext(ctx, listDocsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Doc{}
	for rows.Next() {
		var i Doc
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Path,
			&i.Title,
			&i.ContentHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDoc = `-- name: SoftDeleteDoc :exec
UPDATE docs SET deleted_at = datetime('now')
WHERE id = ? AND workspace_id = ?
`

type SoftDeleteDocParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SoftDeleteDoc(ctx context.Context, arg SoftDeleteDocParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDoc, arg.ID, arg.WorkspaceID)
	return err
}

const updateDocContent = `-- name: UpdateDocContent :exec
UPDATE docs
SET title = ?, content_hash = ?, updated_at = datetime('now')
WHERE id = ? AND workspace_id = ?
`

type UpdateDocContentParams struct {
	Title       string `json:"title"`
	ContentHash string `json:"content_hash"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateDocContent(ctx context.Context, arg UpdateDocContentParams) error {
	_, err := q.db.ExecContext(ctx, updateDocContent,
		arg.Title,
		arg.ContentHash,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}
