// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: graph.sql

package db

import (
	"context"
)

const listBacklinksForGraph = `-- name: ListBacklinksForGraph :many
SELECT src_doc_id, dst_doc_id, anchor_text
FROM backlinks
WHERE src_doc_id IN (SELECT id FROM docs WHERE workspace_id = ? AND deleted_at IS NULL)
`

func (q *Queries) ListBacklinksForGraph(ctx context.Context, workspaceID string) ([]Backlink, error) {
	rows, err := q.db.QueryContext(ctx, listBacklinksForGraph, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backlink{}
	for rows.Next() {
		var i Backlink
		if err := rows.Scan(&i.SrcDocID, &i.DstDocID, &i.AnchorText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocsForGraph = `-- name: ListDocsForGraph :many
SELECT id, title FROM docs
WHERE workspace_id = ? AND deleted_at IS NULL
`

type ListDocsForGraphRow struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) ListDocsForGraph(ctx context.Context, workspaceID string) ([]ListDocsForGraphRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocsForGraph, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocsForGraphRow{}
	for rows.Next() {
		var i ListDocsForGraphRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
