// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indexing.sql

package db

import (
	"context"
	"database/sql"
)

const getDocByID = `-- name: GetDocByID :one
SELECT id, workspace_id, path, title, content_hash, updated_at
FROM docs
WHERE id = ? AND workspace_id = ? AND deleted_at IS NULL
`

type GetDocByIDParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

type GetDocByIDRow struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Path        string `json:"path"`
	Title       string `json:"title"`
	ContentHash string `json:"content_hash"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) GetDocByID(ctx context.Context, arg GetDocByIDParams) (GetDocByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDocByID, arg.ID, arg.WorkspaceID)
	var i GetDocByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Path,
		&i.Title,
		&i.ContentHash,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocByPath = `-- name: GetDocByPath :one
SELECT id, title, content_hash, updated_at
FROM docs
WHERE workspace_id = ? AND path = ? AND deleted_at IS NULL
`

type GetDocByPathParams struct {
	WorkspaceID string `json:"workspace_id"`
	Path        string `json:"path"`
}

type GetDocByPathRow struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	ContentHash string `json:"content_hash"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) GetDocByPath(ctx context.Context, arg GetDocByPathParams) (GetDocByPathRow, error) {
	row := q.db.QueryRowContext(ctx, getDocByPath, arg.WorkspaceID, arg.Path)
	var i GetDocByPathRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContentHash,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, workspace_id, doc_id, line_no, title, due_date, project,
       priority, assignee, done, created_at, updated_at
FROM tasks
WHERE id = ? AND workspace_id = ?
`

type GetTaskByIDParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

type GetTaskByIDRow struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	DocID       string         `json:"doc_id"`
	LineNo      int64          `json:"line_no"`
	Title       string         `json:"title"`
	DueDate     sql.NullString `json:"due_date"`
	Project     sql.NullString `json:"project"`
	Priority    sql.NullString `json:"priority"`
	Assignee    sql.NullString `json:"assignee"`
	Done        int64          `json:"done"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (GetTaskByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, arg.ID, arg.WorkspaceID)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DocID,
		&i.LineNo,
		&i.Title,
		&i.DueDate,
		&i.Project,
		&i.Priority,
		&i.Assignee,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, slug, name, owner_id, created_at
FROM workspaces
WHERE id = ?
`

// Copyright (C) 2026 Zekrost <tech@zekrost.com>
// SPDX-License-Identifier: AGPL-3.0-only
func (q *Queries) GetWorkspaceByID(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDoc = `-- name: UpsertDoc :one
INSERT INTO docs (id, workspace_id, path, title, content_hash, created_by)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(workspace_id, path) DO UPDATE SET
    title = excluded.title,
    content_hash = excluded.content_hash,
    updated_at = datetime('now'),
    deleted_at = NULL
RETURNING id
`

type UpsertDocParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Path        string `json:"path"`
	Title       string `json:"title"`
	ContentHash string `json:"content_hash"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) UpsertDoc(ctx context.Context, arg UpsertDocParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertDoc,
		arg.ID,
		arg.WorkspaceID,
		arg.Path,
		arg.Title,
		arg.ContentHash,
		arg.CreatedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
