// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Attachment struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	DocID       sql.NullString `json:"doc_id"`
	Filename    string         `json:"filename"`
	Mime        string         `json:"mime"`
	SizeBytes   int64          `json:"size_bytes"`
	StorageKey  string         `json:"storage_key"`
	CreatedAt   string         `json:"created_at"`
}

type AuditLog struct {
	ID          int64          `json:"id"`
	WorkspaceID sql.NullString `json:"workspace_id"`
	ActorID     sql.NullString `json:"actor_id"`
	Action      string         `json:"action"`
	Entity      string         `json:"entity"`
	EntityID    string         `json:"entity_id"`
	MetaJson    sql.NullString `json:"meta_json"`
	CreatedAt   string         `json:"created_at"`
}

type Backlink struct {
	SrcDocID   string `json:"src_doc_id"`
	DstDocID   string `json:"dst_doc_id"`
	AnchorText string `json:"anchor_text"`
}

type ChangeLog struct {
	Seq         int64  `json:"seq"`
	WorkspaceID string `json:"workspace_id"`
	Entity      string `json:"entity"`
	EntityID    string `json:"entity_id"`
	Op          string `json:"op"`
	CreatedAt   string `json:"created_at"`
}

type Doc struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	Path        string         `json:"path"`
	Title       string         `json:"title"`
	ContentHash string         `json:"content_hash"`
	CreatedBy   string         `json:"created_by"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	DeletedAt   sql.NullString `json:"deleted_at"`
}

type DocVersion struct {
	ID          int64  `json:"id"`
	DocID       string `json:"doc_id"`
	ContentHash string `json:"content_hash"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

type DocsFt struct {
	DocID   string `json:"doc_id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Membership struct {
	UserID      string `json:"user_id"`
	WorkspaceID string `json:"workspace_id"`
	Role        string `json:"role"`
}

type RefreshToken struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	TokenHash string         `json:"token_hash"`
	ExpiresAt string         `json:"expires_at"`
	RevokedAt sql.NullString `json:"revoked_at"`
}

type SyncCommand struct {
	IdempotencyKey string `json:"idempotency_key"`
	WorkspaceID    string `json:"workspace_id"`
	CommandJson    string `json:"command_json"`
	CreatedAt      string `json:"created_at"`
}

type Task struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	DocID       string         `json:"doc_id"`
	LineNo      int64          `json:"line_no"`
	Title       string         `json:"title"`
	DueDate     sql.NullString `json:"due_date"`
	Project     sql.NullString `json:"project"`
	Priority    sql.NullString `json:"priority"`
	Assignee    sql.NullString `json:"assignee"`
	Done        int64          `json:"done"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	InProgress  int64          `json:"in_progress"`
}

type User struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	CreatedAt    string `json:"created_at"`
}

type Webhook struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Url         string `json:"url"`
	Secret      string `json:"secret"`
	Events      string `json:"events"`
	Active      int64  `json:"active"`
	CreatedAt   string `json:"created_at"`
}

type Workspace struct {
	ID        string `json:"id"`
	Slug      string `json:"slug"`
	Name      string `json:"name"`
	OwnerID   string `json:"owner_id"`
	CreatedAt string `json:"created_at"`
}
