// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddMembership(ctx context.Context, arg AddMembershipParams) error
	CountUsers(ctx context.Context) (int64, error)
	// Copyright (C) 2026 Zekrost <tech@zekrost.com>
	// SPDX-License-Identifier: AGPL-3.0-only
	CreateDoc(ctx context.Context, arg CreateDocParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	// Copyright (C) 2026 Zekrost <tech@zekrost.com>
	// SPDX-License-Identifier: AGPL-3.0-only
	CreateUser(ctx context.Context, arg CreateUserParams) error
	// Copyright (C) 2026 Zekrost <tech@zekrost.com>
	// SPDX-License-Identifier: AGPL-3.0-only
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteTasksForDoc(ctx context.Context, docID string) error
	GetChangesAfter(ctx context.Context, arg GetChangesAfterParams) ([]ChangeLog, error)
	GetDoc(ctx context.Context, arg GetDocParams) (Doc, error)
	GetDocByID(ctx context.Context, arg GetDocByIDParams) (GetDocByIDRow, error)
	GetDocByPath(ctx context.Context, arg GetDocByPathParams) (GetDocByPathRow, error)
	GetDocVersions(ctx context.Context, arg GetDocVersionsParams) ([]GetDocVersionsRow, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetRefreshTokenByID(ctx context.Context, id string) (RefreshToken, error)
	GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (GetTaskByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	// Copyright (C) 2026 Zekrost <tech@zekrost.com>
	// SPDX-License-Identifier: AGPL-3.0-only
	GetWorkspaceByID(ctx context.Context, id string) (Workspace, error)
	// Copyright (C) 2026 Zekrost <tech@zekrost.com>
	// SPDX-License-Identifier: AGPL-3.0-only
	// Sync delta (seccion 9): cursor monotono por workspace + push con
	// deduplicacion por idempotency-key.
	InsertChange(ctx context.Context, arg InsertChangeParams) (InsertChangeRow, error)
	InsertDocVersion(ctx context.Context, arg InsertDocVersionParams) error
	IsCommandProcessed(ctx context.Context, arg IsCommandProcessedParams) (int64, error)
	LastChangeSeq(ctx context.Context, workspaceID string) (int64, error)
	ListBacklinksForGraph(ctx context.Context, workspaceID string) ([]Backlink, error)
	ListDocsByWorkspace(ctx context.Context, workspaceID string) ([]Doc, error)
	ListDocsForGraph(ctx context.Context, workspaceID string) ([]ListDocsForGraphRow, error)
	ListTasksByDateRange(ctx context.Context, arg ListTasksByDateRangeParams) ([]Task, error)
	ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error)
	// Copyright (C) 2026 Zekrost <tech@zekrost.com>
	// SPDX-License-Identifier: AGPL-3.0-only
	ListTasksByWorkspace(ctx context.Context, arg ListTasksByWorkspaceParams) ([]Task, error)
	ListTasksDueToday(ctx context.Context, arg ListTasksDueTodayParams) ([]Task, error)
	ListTasksMineToday(ctx context.Context, arg ListTasksMineTodayParams) ([]Task, error)
	ListWorkspacesByUser(ctx context.Context, userID string) ([]ListWorkspacesByUserRow, error)
	MarkCommandProcessed(ctx context.Context, arg MarkCommandProcessedParams) error
	RevokeRefreshToken(ctx context.Context, id string) error
	SetDocUpdatedAt(ctx context.Context, arg SetDocUpdatedAtParams) error
	SetTaskDone(ctx context.Context, arg SetTaskDoneParams) error
	SoftDeleteDoc(ctx context.Context, arg SoftDeleteDocParams) error
	UpdateDocContent(ctx context.Context, arg UpdateDocContentParams) error
	UpsertDoc(ctx context.Context, arg UpsertDocParams) (string, error)
	UpsertTask(ctx context.Context, arg UpsertTaskParams) error
}

var _ Querier = (*Queries)(nil)
