// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"
)

const getChangesAfter = `-- name: GetChangesAfter :many
SELECT seq, workspace_id, entity, entity_id, op, created_at
FROM change_log
WHERE workspace_id = ? AND seq > ?
ORDER BY seq ASC
LIMIT ?
`

type GetChangesAfterParams struct {
	WorkspaceID string `json:"workspace_id"`
	Seq         int64  `json:"seq"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) GetChangesAfter(ctx context.Context, arg GetChangesAfterParams) ([]ChangeLog, error) {
	rows, err := q.db.QueryContext(ctx, getChangesAfter, arg.WorkspaceID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangeLog{}
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.Seq,
			&i.WorkspaceID,
			&i.Entity,
			&i.EntityID,
			&i.Op,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocVersions = `-- name: GetDocVersions :many
SELECT doc_id, content_hash, created_at, created_by
FROM doc_versions
WHERE doc_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type GetDocVersionsParams struct {
	DocID string `json:"doc_id"`
	Limit int64  `json:"limit"`
}

type GetDocVersionsRow struct {
	DocID       string `json:"doc_id"`
	ContentHash string `json:"content_hash"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) GetDocVersions(ctx context.Context, arg GetDocVersionsParams) ([]GetDocVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocVersions, arg.DocID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocVersionsRow{}
	for rows.Next() {
		var i GetDocVersionsRow
		if err := rows.Scan(
			&i.DocID,
			&i.ContentHash,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChange = `-- name: InsertChange :one

INSERT INTO change_log (workspace_id, entity, entity_id, op)
VALUES (?, ?, ?, ?)
RETURNING seq, created_at
`

type InsertChangeParams struct {
	WorkspaceID string `json:"workspace_id"`
	Entity      string `json:"entity"`
	EntityID    string `json:"entity_id"`
	Op          string `json:"op"`
}

type InsertChangeRow struct {
	Seq       int64  `json:"seq"`
	CreatedAt string `json:"created_at"`
}

// Copyright (C) 2026 Zekrost <tech@zekrost.com>
// SPDX-License-Identifier: AGPL-3.0-only
// Sync delta (seccion 9): cursor monotono por workspace + push con
// deduplicacion por idempotency-key.
func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) (InsertChangeRow, error) {
	row := q.db.QueryRowContext(ctx, insertChange,
		arg.WorkspaceID,
		arg.Entity,
		arg.EntityID,
		arg.Op,
	)
	var i InsertChangeRow
	err := row.Scan(&i.Seq, &i.CreatedAt)
	return i, err
}

const insertDocVersion = `-- name: InsertDocVersion :exec
INSERT INTO doc_versions (doc_id, content_hash, created_at, created_by)
VALUES (?, ?, datetime('now'), ?)
`

type InsertDocVersionParams struct {
	DocID       string `json:"doc_id"`
	ContentHash string `json:"content_hash"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) InsertDocVersion(ctx context.Context, arg InsertDocVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertDocVersion, arg.DocID, arg.ContentHash, arg.CreatedBy)
	return err
}

const isCommandProcessed = `-- name: IsCommandProcessed :one
SELECT 1 FROM sync_commands WHERE idempotency_key = ? AND workspace_id = ?
`

type IsCommandProcessedParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	WorkspaceID    string `json:"workspace_id"`
}

func (q *Queries) IsCommandProcessed(ctx context.Context, arg IsCommandProcessedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isCommandProcessed, arg.IdempotencyKey, arg.WorkspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const lastChangeSeq = `-- name: LastChangeSeq :one
SELECT seq FROM change_log
WHERE workspace_id = ?
ORDER BY seq DESC
LIMIT 1
`

func (q *Queries) LastChangeSeq(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastChangeSeq, workspaceID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const markCommandProcessed = `-- name: MarkCommandProcessed :exec
INSERT INTO sync_commands (idempotency_key, workspace_id, command_json)
VALUES (?, ?, ?)
`

type MarkCommandProcessedParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	WorkspaceID    string `json:"workspace_id"`
	CommandJson    string `json:"command_json"`
}

func (q *Queries) MarkCommandProcessed(ctx context.Context, arg MarkCommandProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markCommandProcessed, arg.IdempotencyKey, arg.WorkspaceID, arg.CommandJson)
	return err
}
