// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const deleteTasksForDoc = `-- name: DeleteTasksForDoc :exec
DELETE FROM tasks WHERE doc_id = ?
`

func (q *Queries) DeleteTasksForDoc(ctx context.Context, docID string) error {
	_, err := q.db.ExecContext(ctx, deleteTasksForDoc, docID)
	return err
}

const listTasksByDateRange = `-- name: ListTasksByDateRange :many
SELECT id, workspace_id, doc_id, line_no, title, due_date, project,
       priority, assignee, done, created_at, updated_at
FROM tasks
WHERE workspace_id = ? AND due_date >= ? AND due_date <= ?
ORDER BY due_date ASC, done ASC
`

type ListTasksByDateRangeParams struct {
	WorkspaceID string         `json:"workspace_id"`
	DueDate     sql.NullString `json:"due_date"`
	DueDate_2   sql.NullString `json:"due_date_2"`
}

func (q *Queries) ListTasksByDateRange(ctx context.Context, arg ListTasksByDateRangeParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByDateRange, arg.WorkspaceID, arg.DueDate, arg.DueDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocID,
			&i.LineNo,
			&i.Title,
			&i.DueDate,
			&i.Project,
			&i.Priority,
			&i.Assignee,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, workspace_id, doc_id, line_no, title, due_date, project,
       priority, assignee, done, created_at, updated_at
FROM tasks
WHERE workspace_id = ? AND project = ?
ORDER BY due_date ASC
`

type ListTasksByProjectParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Project     sql.NullString `json:"project"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByProject, arg.WorkspaceID, arg.Project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocID,
			&i.LineNo,
			&i.Title,
			&i.DueDate,
			&i.Project,
			&i.Priority,
			&i.Assignee,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByWorkspace = `-- name: ListTasksByWorkspace :many
SELECT id, workspace_id, doc_id, line_no, title, due_date, project,
       priority, assignee, done, created_at, updated_at
FROM tasks
WHERE workspace_id = ? AND done = ?
ORDER BY done ASC, due_date ASC
`

type ListTasksByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Done        int64  `json:"done"`
}

func (q *Queries) ListTasksByWorkspace(ctx context.Context, arg ListTasksByWorkspaceParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByWorkspace, arg.WorkspaceID, arg.Done)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocID,
			&i.LineNo,
			&i.Title,
			&i.DueDate,
			&i.Project,
			&i.Priority,
			&i.Assignee,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksDueToday = `-- name: ListTasksDueToday :many
SELECT id, workspace_id, doc_id, line_no, title, due_date, project,
       priority, assignee, done, created_at, updated_at
FROM tasks
WHERE workspace_id = ? AND assignee = ?
  AND due_date <= date('now') AND done = 0
ORDER BY due_date ASC
`

type ListTasksDueTodayParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Assignee    sql.NullString `json:"assignee"`
}

func (q *Queries) ListTasksDueToday(ctx context.Context, arg ListTasksDueTodayParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksDueToday, arg.WorkspaceID, arg.Assignee)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocID,
			&i.LineNo,
			&i.Title,
			&i.DueDate,
			&i.Project,
			&i.Priority,
			&i.Assignee,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksMineToday = `-- name: ListTasksMineToday :many
SELECT id, workspace_id, doc_id, line_no, title, due_date, project,
       priority, assignee, done, created_at, updated_at
FROM tasks
WHERE workspace_id = ? AND assignee = ? AND due_date <= date('now') AND done = 0
ORDER BY due_date ASC
`

type ListTasksMineTodayParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Assignee    sql.NullString `json:"assignee"`
}

func (q *Queries) ListTasksMineToday(ctx context.Context, arg ListTasksMineTodayParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksMineToday, arg.WorkspaceID, arg.Assignee)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocID,
			&i.LineNo,
			&i.Title,
			&i.DueDate,
			&i.Project,
			&i.Priority,
			&i.Assignee,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskDone = `-- name: SetTaskDone :exec
UPDATE tasks SET done = ?, updated_at = datetime('now')
WHERE id = ? AND workspace_id = ?
`

type SetTaskDoneParams struct {
	Done        int64  `json:"done"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SetTaskDone(ctx context.Context, arg SetTaskDoneParams) error {
	_, err := q.db.ExecContext(ctx, setTaskDone, arg.Done, arg.ID, arg.WorkspaceID)
	return err
}

const upsertTask = `-- name: UpsertTask :exec
INSERT INTO tasks (id, workspace_id, doc_id, line_no, title, due_date,
                   project, priority, assignee, done)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (doc_id, line_no) DO UPDATE SET
    title = excluded.title,
    due_date = excluded.due_date,
    project = excluded.project,
    priority = excluded.priority,
    assignee = excluded.assignee,
    done = excluded.done,
    updated_at = datetime('now')
`

type UpsertTaskParams struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	DocID       string         `json:"doc_id"`
	LineNo      int64          `json:"line_no"`
	Title       string         `json:"title"`
	DueDate     sql.NullString `json:"due_date"`
	Project     sql.NullString `json:"project"`
	Priority    sql.NullString `json:"priority"`
	Assignee    sql.NullString `json:"assignee"`
	Done        int64          `json:"done"`
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, upsertTask,
		arg.ID,
		arg.WorkspaceID,
		arg.DocID,
		arg.LineNo,
		arg.Title,
		arg.DueDate,
		arg.Project,
		arg.Priority,
		arg.Assignee,
		arg.Done,
	)
	return err
}
