// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"
)

const addMembership = `-- name: AddMembership :exec
INSERT INTO memberships (user_id, workspace_id, role)
VALUES (?, ?, ?)
`

type AddMembershipParams struct {
	UserID      string `json:"user_id"`
	WorkspaceID string `json:"workspace_id"`
	Role        string `json:"role"`
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) error {
	_, err := q.db.ExecContext(ctx, addMembership, arg.UserID, arg.WorkspaceID, arg.Role)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (id, slug, name, owner_id)
VALUES (?, ?, ?, ?)
`

type CreateWorkspaceParams struct {
	ID      string `json:"id"`
	Slug    string `json:"slug"`
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.OwnerID,
	)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT user_id, workspace_id, role
FROM memberships
WHERE user_id = ? AND workspace_id = ?
`

type GetMembershipParams struct {
	UserID      string `json:"user_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, getMembership, arg.UserID, arg.WorkspaceID)
	var i Membership
	err := row.Scan(&i.UserID, &i.WorkspaceID, &i.Role)
	return i, err
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT w.id, w.slug, w.name, w.owner_id, w.created_at, m.role
FROM workspaces w
JOIN memberships m ON m.workspace_id = w.id
WHERE m.user_id = ?
ORDER BY w.created_at DESC
`

type ListWorkspacesByUserRow struct {
	ID        string `json:"id"`
	Slug      string `json:"slug"`
	Name      string `json:"name"`
	OwnerID   string `json:"owner_id"`
	CreatedAt string `json:"created_at"`
	Role      string `json:"role"`
}

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID string) ([]ListWorkspacesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesByUserRow{}
	for rows.Next() {
		var i ListWorkspacesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
